AmbuTrans/Controllers/MedicalTransferViewController.cs
using AmbuTrans.DataLayer.Repository;
using AmbuTrans.Helper;
using AmbuTrans.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AmbuTrans.Controllers
{
    public class MedicalTransferViewController : Controller
    {
        private readonly MedicalTransferRepository _repo;
        public MedicalTransferViewController()
        {

            _repo = new MedicalTransferRepository();
        }
        public ActionResult Index()
        {
            if (Session["UserID"] != null)
            {
                ViewBag.breadcrumbModel = new BreadcrumbModel() { subActionTitle = "View Patient Details" };
                IQueryable<ViewMedicalTransferFormModel> List = _repo.GetAllMedicalTransferDetails();
                return View(List);
            }
            else
                return RedirectToAction("Login", "AdminAccount");
        }
        public ActionResult ReportView(int MedicalTransferID)
        {
            ResponseModel<ViewMedicalTransferModel> mResult = _repo.ViewMedicalTransferReport(MedicalTransferID);
            return View(mResult.Result);
        }
        public ActionResult Open(int MedicalTransferID)
        {
            ResponseModel<bool> mResult = new ResponseModel<bool>();
            bool obj = _repo.OpenReport(MedicalTransferID);
            if (obj == true)
            {
                mResult.Status = ResponseStatus.Success;
                mResult.Message = "User open.";
            }
            TempData["alertModel"] = new AlertModel(mResult.Status == ResponseStatus.Success ? AlertStatus.success : AlertStatus.danger, mResult.Message);
            return Redirect(Url.Action("Index"));

        }
        public ActionResult Closed(int MedicalTransferID)
        {
            ResponseModel<bool> mResult = new ResponseModel<bool>();
            bool obj = _repo.ClosedReport(MedicalTransferID);
            if (obj == true)
            {
                mResult.Status = ResponseStatus.Success;
                mResult.Message = "User Closed.";
            }
            TempData["alertModel"] = new AlertModel(mResult.Status == ResponseStatus.Success ? AlertStatus.success : AlertStatus.danger, mResult.Message);
            return Redirect(Url.Action("Index"));
        }
        [HttpPost]
        public JsonResult Delete(int Id)
        {
            ResponseModel<object> mResult = _repo.DeleteTransferDetails(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

    }
}

AmbuTrans/Views/MedicalTransferView/Index.cshtml
@model IEnumerable<ViewMedicalTransferFormModel>
@using GridMvc.Html
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@helper ActionButtons(int Id, bool isActive)
{
if (isActive)
{
        <a href="@Url.Action("Closed", "MedicalTransferView", new { @MedicalTransferID = Id, @filter = Request.QueryString })" class="btn btn-warning btn-primary">
             Close
        </a>
}
else
{
        <a href="@Url.Action("Open", "MedicalTransferView", new { @MedicalTransferID = Id, @filter = Request.QueryString })" class="btn btn-success btn-primary btn-blue">Open
        </a>
}
    <a href="javascript:;" class="btn btn-danger btn-primary btn-red deleteData" data-id="@Id">
        <i class="icon-trash-o"></i> Delete
    </a>

}
@helper ViewPDF(string PdfPath, bool isPdf)
{
if (isPdf)
{
        <a href="@PdfPath" class="btn btn-success btn-primary btn-grey" target="_blank">
            <i class="fa fade"></i>View PDF
        </a>
}
}
@helper Date(DateTime dt)
        {
    @dt.ToString(GlobalConfig.DateFormat)
}

@Styles.Render("~/css/gridMvc")
<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">All Patient Reports</h4>

                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">

                        <div id="basicScenario" class="jsgrid" style="position: relative;height: auto;width: 100%;">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {
                               column.Add(t => t.PatientName)
                               .Titled("Patient Name")
                               .Filterable(true)
                               .Sortable(true)
                               .Encoded(false).Sanitized(false);

                               column.Add(t => t.ContactPerson)
                              .Titled("ContactPerson")
                              .Filterable(true)
                              .Sortable(true)
                              .Encoded(false).Sanitized(false);

                               column.Add(t => t.AddedDate)
                              .Titled("Register Date")
                              .Filterable(true)
                              .Sortable(true)
                              .Encoded(false).Sanitized(false)
                                .RenderValueAs(x => Date(x.AddedDate));

                               column.Add()
                           .Encoded(false)
                           .Sanitized(false)
                           .Titled("View PDF")
                           .RenderValueAs(x => ViewPDF(x.PDFPath, x.isPdf));

                               column.Add()
                             .Encoded(false)
                             .Sanitized(false)
                             .Titled("Action")
                             .RenderValueAs(x => ActionButtons(x.MedicalTransferID, x.isActive)).SetWidth(300);


                           }).Selectable(false).WithPaging(10)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/jQuery/gridMvc")
    <script type="text/javascript">
        ActiveMenu("MedicalTransferView");

         $(function () {
            $(".deleteData").click(function () {
                deleteRow($(this), '@Url.Action("Delete")');
            });
        });
    </script>
}